### ISSUE TITLE
Finalize Project Name

### ISSUE THREAD

**Issue by ArthurCose** [Hub-OS/Hub-OS#106]
We need a new project name for searchability and more. This is important to resolve as it will decide the GitHub repo name (possibly breaking current clones/forks) and the website's domain name.

Starting points:
 - Relating to the internet or cyberspace
 - Relating to AI
   - Note modern AI likely won't be built in, but someone might be able to script the right connections with #105
 - Relating to battling
 - Relating to community
 - Relating to modding or possibilities
 - A Megaman Battle Network boss such as relating to phoenixes for Falzar

Aiming for an acronym instead of initialism has been suggested, similar to `Raid on Phoenix Hill` or `RoPH` (pronounced rough)

A two word name with one initialism could be used as well, similar to `F-Zero` (Friction Zero) or `CNET` (Computer Network)
  - M-Combat (Modular/Modifiable Combat)

**Comment by HimoriK** [comment]
4 suggestions are:

Combat Network (CN or COM-N removed)
Combat Action Network (CAN or CN)
Combat Matrix (COM)
Advanced Netbattle Action (ANA)

**Comment by ArthurCose** [comment]
More ideas:
  - VisionBurst (or something involving VisionBurst)
  - Project WWW
  - GridGospel
  - Something involving Stream or Protocol
