### ISSUE TITLE
Display player names in overworld

### ISSUE THREAD

**Issue by ArthurCose** [Hub-OS/Hub-OS#115]
Not certain on where / when to display names:

Possible ways to activate:
- Hovering with a mouse
- Standing near another player
- Other?

Places to display:
- Below the player (may be hard to read / clutter)
- Above the player (may conflict with emotes)
- On the mouse
- Other?

**Comment by HimoriK** [comment]
Hover over with mouse.
Player profile 'more info' options with battle data ala pokemon badges

Text can display under the player or slightly off center to the right of the mouse
Can also toggle to always have viewable player names
